db.program.insert({
    "datenum" : 21,
    "datemonth" : "jún",
    "datemonth_en": "June",
    "datetime" : "20:30",
    "place" : "Hlavné námestie",
    "place_en": "Main Square",
    "title" : "Sen noci svätojánskej",
    "title_en": "A Midsummer Night’s Dream",
    "intro" : "Otvárací koncert 10. ročníka Viva Musica! festivalu a Kultúrneho leta a Hradných slávností Bratislava 2014",
    "intro_en": "Opening concert in the 10th and Castle Festival 2014",
    "text" : "Viva Musica! festival v roku 2014 oslavuje okrúhle 10. narodeniny a svojim návštevníkom opäť ponúkne niekoľko exkluzívnych hudobných zážitkov. V rámci otváracieho koncertu uvedieme v spolupráci s medzinárodným festivalom Letné shakespearovské slávnosti a Kultúrne leto a hradné slávnosti Bratislava 2014 Shakespearovu romantickú komédiu <em>Sen noci svätojánskej</em> s rovnomennou scénickou hudbou nemeckého hudobného skladateľa Felixa Mendelssohna-Bartholdyho (1809-1847). Shakespearov text ožije v podaní Sabiny Laurinovej, Oldřicha Víznera a Csongora Kassaia v sprievode Mendelssohnovej hudby interpretovanej Slovenskou filharmóniou pod vedením Leoša Svárovského. Viva Shakespeare! Realizačný tím:<br /><br />Preklad: Martin Hilský, Ľubomír Feldek<br />Dramaturgia a réžia: Róbert Mankovecký<br />Producent za LSS: Janka Zednikovičová<br /><br />Účinkujú:<br /><br />Oberon – Oldřich Vízner<br />Titania – Sabina Laurinová<br />Puk – Csongor Kassai<br />Klbko – Peter Kadlečík<br />Väzba – Jakub Rybárik<br /><br />Petronela Drobná – soprán<br />Katarína Kubovičová-Sroková – alt<br />Ženský spevácky zbor<br />Jozef Chabroň – zbormajster<br /><br />Slovenská filharmónia<br />Leoš Svárovský – dirigent",
    "text_en": "In 2014 the Viva Musica! Festival celebrates its 10th some exquisite musical delights. In collaboration with the international Summer Shakespeare Festival, Bratislava Cultural Summer and Castle Festival 2014, our opening concert presents Shakespeare’s romantic comedy A Midsummer Night’s Dream with the identically-named music by the German composer Felix Mendelssohn-Bartholdy (1809-1847). Shakespeare’s text is vividly rendered by Sabina Laurinová, Oldřich Vízner and Csongor Kassai, accompanied by Mendelssohn’s music performed by the Slovak Philharmonic and members of the Slovak Philharmonic Choir conducted by Leoš Svárovský. Viva Shakespeare!<br /><br /><b>Production team:</b><br /><br />Translators: Martin Hilský, Ľubomír Feldek<br />Dramaturge and director: Róbert Mankovecký<br />Producer for SSF: Janka Zednikovičová<br /><br /><b>Performers:</b><br /><br />Oberon – Oldřich Vízner<br />Titania – Sabina Laurinová<br />Puck – Csongor Kassai<br />Bottom – Peter Kadlečík<br />Quince – Jakub Rybárik<br /><br />Petronela Drobná – soprano<br />Katarína Kubovičová-Sroková – alto<br />Members of the Slovak Philharmonic Choir<br />Jozef Chabroň –choirmaster<br /><br />Slovak Philharmonic<br />Leoš Svárovský – conductor",
    "img" : "sen.jpg",
    "path" : "sen-noci-svatojanskej",
    "tickets" : "",
    "price" : "Vstup voľný",
    "price_en": "Entrance free"
})
db.program.insert({
    "datenum" : 22,
    "datemonth" : "jún",
    "datemonth_en" : "June",
    "datetime" : "17:00",
    "place" : "Nádvorie Primaciálneho paláca",
    "place_en": "Primatial Palace Forecourt",
    "title" : "Čarovná flauta",
    "title_en": "The Magic Flute",
    "intro" : "Detský deň v rámci Viva Musica! festivalu na obľúbenom Hlavnom námestí a na Nádvorí Primaciálneho paláca prinesie okrem iného aj netradičné spracovanie opernej klasiky pre deti.",
    "intro_en": "The famous Mozart opera as you’ve never known it!",
    "text" : "Mozartova opera Čarovná flauta rozpráva príbeh princa Tamina, ktorý bojuje o priazeň pôvabnej princeznej Paminy, dcéry Kráľovnej noci, a vtáčkara Papagena túžiaceho po krásnej Papagene. Silou lásky a pravdy hrdinovia prekonávajú nástrahy Kráľovnej noci, jej troch dvorných dám a sluhu Monostata. Mozartova opera v podaní pražského Národného bábkového divadla je určená predovšetkým deťom a ich rodičom a prinesie okrem stretnutia s operou a hudbou rakúskeho génia aj nevšedný zážitok z vizuálneho stvárnenia diela v podaní bábok so živými hercami.",
    "text_en": "Mozart’s opera <em>The Magic Flute</em> tells the story of prince Tamino, who is fighting for the favour of the charming princess Pamina, daughter of the Queen of the Night, and the bird-catcher Papageno who is full of desire for the beautiful Papagena. By the power of love and truth the heroes overcome the snares of the Queen of the Night, her three court ladies and her servant Monostato. Mozart’s opera, as rendered by the Prague National Marionette Theatre, is designed principally for children and their parents, and apart from the encounter with the work and music of the Austrian genius, offers an unusual treat in the visual presentation of the work as rendered by puppets with live actors. Martin Vanek will be the accompanist during the performance.",
    "img" : "babkova.jpg",
    "path" : "carovna-flauta",
    "tickets" : "",
    "price" : ""
})
db.program.insert({
    "datenum" : 22,
    "datemonth" : "jún",
    "datemonth_en" : "June",
    "datetime" : "20:00",
    "place" : "Hlavné námestie",
    "place_en": "Main Square",
    "title" : "VIRTUOSO",
    "title_en" : "VIRTUOSO",
    "intro" : "Predstavte si obrovský orchester zložený z talentovaných detí z celého Slovenska – detí, ktoré by sa za normálnych okolností možno nikdy nestretli...",
    "intro_en": "Imagine an enormous orchestra composed of talented children from the whole of Slovakia – children you would never meet under normal circumstances...",
    "text" : "Predstavte si obrovský orchester zložený z talentovaných detí z celého Slovenska – detí, ktoré by sa za normálnych okoSpojila ich však láska k hudbe, hodiny cvičenia na hudobnom nástroji a možno aj v kútiku duše schovaný sen stať sa niekým, kto sa zapíše do hudobných dejín. Unikátny hudobný projekt VIRTUOSO túto predstavu premieňa na realitu prostredníctvom zapojenia detských a mládežníckych talentov zo základných umeleckých škôl z celého Slovenska do jedného veľkého národného orchestra. Šéfdirigentom orchestra je Igor Dohovič, rodák z Prešova, pod ktorého vedením už národný mládežnícky orchester úspešne absolvoval niekoľko koncertov po celom Slovensku. V orchestri platí pravidlo: „Jeden za všetkých – všetci za lásku ku klasickej hudbe!“ A tá je prudko nákazlivá aj pre všetkých ostatných.",
    "text_en": "But what all of them had in common was a love of music, hours of practice on a musical instrument, and maybe in some corner of their minds a dream of becoming someone whose name would be recorded in musical history. The unique musical project VIRTUOSO makes this idea a reality by bringing together talented children and youth from the primary art schools of all Slovakia into one big national orchestra. The chief conductor is Igor Dohovič, a native of Prešov, under whose direction the orchestra has already successfully completed a number of concerts throughout Slovakia. In this orchestra the rule applies: <em>“One for all, and all for the love of classical music!”</em> And that is highly infectious for everyone else.",
    "img" : "virtuoso.jpg",
    "path" : "virtuoso",
    "tickets" : "",
    "price" : "Vstup voľný"
})
db.program.insert({
    "datenum" : 24,
    "datemonth" : "jún",
    "datemonth": "June",
    "datetime" : "20:00",
    "place" : "Stará tržnica",
    "place_en": "Old City Market Hall",
    "title" : "Quasars Ensemble & Dalibor Karvay",
    "title_en": "Quasars Ensemble & Dalibor Karvay",
    "intro" : "Jedinečné spojenie hviezd súčasnej klasiky a husľového virtuóza Dalibora Karvaya.",
    "intro_en": "A unique alliance of stars of contemporary classical music with the violin virtuoso Dalibor Karvay.",
    "text" : "Komorné zoskupenie Quasars Ensemble pôsobí na slovenskej hudobnej scéne od roku 2008 a počas šiestich rokov sa vyprovilovalo na medzinárodne uznávaný súbor súčasnej klasickej hudby. Quasars Ensemble založil hudobný skladateľ, klavirista a dirigent Ivan Buffa a výnimočnosťou súboru je okrem iného aj fakt, že popri súčasnej klasickej hudbe sa v rovnakej miere venuje aj hudbe starších epoch. Súbor je pravidelným hosťom významných domácich i zahraničných hudobných festivalov, organizuje vlastné projekty v regiónoch Slovenska, má na konte šesť profilových CD albumov a je držiteľom ocenenia Krištáľové krídlo v kategórii „Hudba“ za rok 2013. Špeciálnym hosťom koncertu bude vynikajúci slovenský huslista Dalibor Karvay, ktorý v sprievode Quasars Ensemble pod taktovkou Ivana Buffu uvedie Waxmanovu verziu melódií z Bizetovej opery <em>Carmen</em> a Ravelovu virtuóznu skladbu <em>Tzigane</em>, ktoré v programe doplní <em>Septet</em> francúzskeho skladateľa s poľskými koreňmi Alexandra Tansmana a <em>Komorná hudba</em> č. 1, op. 24 nemeckého autora Paula Hindemitha.<br /><br />PROGRAM:<br /><br />Alexandre Tansman (1897-1986): <em>Septet</em><br />Maurice Ravel (1875-1937): <em>Tzigane</em> (arr. I. Buffa)<br />Franz Waxman (1906-1967): <em>Carmen Fantasie</em> (arr. I. Buffa)<br />Paul Hindemith (1895-1963): <em>Komorná hudba</em> č. 1, op. 24",
    "text_en": "The chamber formation Quasars Ensemble has been active on the Slovak music scene since 2008, and in the course of six years has established its profile as an internationally respected formation in contemporary classical music. Quasars Ensemble was founded by the composer, pianist and conductor Ivan Buffa, and one of its exceptional features is that alongside contemporary classical music it also devotes itself in equal measure to the music of earlier epochs. The ensemble is a regular guest at leading music festivals at home and abroad, organises projects of its own in the regions of Slovakia, has six profile CD albums to its credit, and is the holder of the 2013 Crystal Wing Prize in the “Music” category. The concert’s special guest will be the outstanding Slovak violinist Dalibor Karvay, who, accompanied by Quasars Ensemble, will present the Waxman version of melodies from Bizet’s opera <em>Carmen</em> and Ravel’s virtuoso work <em>Tzigane</em>. These will be complemented in the programme by <em>Septet</em>, a work by the French composer (with Polish roots) Alexander Tansman, <em>Divertimento</em> Op. 11 by the Slovak composer Alexander Moyzes, and <em>Chamber Music</em> No. 1, Op. 24 by the German composer Paul Hindemith.",
    "img" : "festival.jpg",
    "path" : "quasars-ensemble-dalibor-karvay",
    "tickets" : "",
    "price" : ""
})
db.program.insert({
    "datenum" : 25,
    "datemonth" : "jún",
    "datemonth_en" : "June",
    "datetime" : "20:00",
    "place" : "Stará tržnica",
    "place_en": "Old City Market Hall",
    "title" : "XAVIER SABATA & IL POMO D’ORO",
    "title_en" : "XAVIER SABATA & IL POMO D’ORO",
    "intro" : "„Tento projekt patrí k tomu najinteligentnejšiemu a najpozoruhodnejšiemu, čo sa v hudobnom svete zrodilo za posledné roky.“ (Guardian)",
    "intro_en": "“This project is one of the most intelligent and noteworthy that the music world has produced in recent years.” (Guardian)",
    "text" : "Španielsky kontratenorista Xavier Sabata vo svojom projekte Händel: Bad Guys odhaľuje svet záporných postáv v Händlových operách a presviedča nás o tom, že baroková opera nemusí byť len o vznešených antických ideáloch. Vďaka svojmu výnimočnému hlasu stvárňuje postavy bezočivých pokrytcov, zlomyseľných tyranov či dokonca obyčajných hlupákov s absolútnym nadhľadom a ľahkosťou. Xavier Sabata pochádza z Barcelony a má za sebou hosťovania na tých najprestížnejších svetových operných a koncertných pódiách. Do Bratislavy príde po prvýkrát so súborom Il pomo d’oro pod vedením huslistu a dirigenta Riccarda Minasiho, ktorý sa špecializuje na tzv. historicky poučenú interpretáciu starej hudby na dobových nástrojoch.<br /><br /><b>PROGRAM:</b><br /><br /><strong>Georg Friedrich Händel</strong> (1685-1759):<br /><br />Sinfonia B dur, HWV 339 (1. časť)<br />Vo‘ dar pace a un’alma altiera (Tamerlano)<br />Nella terra, in ciel, nell‘onda (Faramondo)<br />Concerto grosso G dur, HWV 314<br />Bel labbro formato (Ottone, re di Germania)<br />Dover, giustizia, amor (Ariodante)<br /><br />* * *<br /><br />Domerò la tua fierezza (Giulio Cesare)<br />Serenatevi, o luci belle (Teseo)<br />Se l’inganno sortisce felice (Ariodante)<br />Sonáta G dur op. 5, č. 4, HWV 399<br />Così suole a rio vicina (Faramondo)<br />Voglio stragi, e voglio morte (Teseo)",
    "text_en": "In his project <em>Händel: Bad Guys</em> the Spanish countertenor Xavier Sabata uncovers the world of the negative characters in Händel’s operas and persuades us of the fact that baroque opera need not only be about the sublime ideals of antiquity. Making use of his exceptional voice, he creates the characters of ruthless hypocrites, malignant tyrants, and pure-and-simple stupid asses, with absolute clarity and ease. Xavier Sabata comes from Barcelona and has a history of guest appearances on the world’s most prestigious opera and concert stages. He is coming to Bratislava for the first time with Il pomo d’oro ensemble, led by violinist and conductor Riccardo Minasi, who specialises in the so-called historically informed performance of early music on period instruments.",
    "img" : "sabata.jpg",
    "path" : "handel-bad-guys",
    "tickets" : "http://www.ticketportal.sk/event.aspx?id=19543&idpartner=57",
    "price" : "do 31. mája 2014: 25,- / 20,- / 15,- EUR"
})
db.program.insert({
    "datenum" : 26,
    "datemonth" : "jún",
    "datemonth_en": "June",
    "datetime" : "20:00",
    "place" : "Stará tržnica",
    "place_en": "Old City Market Hall",
    "title" : "Korben Dallas Symphony",
    "title_en" : "Korben Dallas Symphony",
    "intro" : "Výnimočný objav slovenskej hudobnej scény v sprievode orchestra na Viva Musica! festivale.",
    "intro_en": "Underground goes classic!",
    "text" : "Korben Dallas minulý rok pokrstil svoj druhý album Karnevalová vrana. V éteri bodujú hity Otec, Zlatý jeleň a Beh a po rokoch v hudobnom podzemí sa Korben Dallas stáva mienkotvornou kapelou. Skupinu založili spevák a gitarista Juraj Benetin a basgitarista Lukáš Fila po rozpade skupiny Appendix, v ktorej spolu hrali trinásť rokov. Bubeníkom sa po dlhom hľadaní stal Ozo Guttler zo skupiny Tu v Dome. Kapela debutovala živým albumom Pekné cesty v roku 2011 a má za sebou okrem hrania v rámci niekoľkých hudobných festivalov aj spoločné koncerty s americkou pesničkárkou Jess Klein, spoluprácu s Ľubom Petruškom z Chiki liki tu-a či s Andrejom Šebanom. S orchestrom však Korben Dallas ešte nikdy nehral – v exkluzívnej premiére po prvýkrát na Viva Musica! festivale!",
    "text_en": "Last year Korben Dallas named his second album <em>Carnival Raven</em>. The hit tunes <em>Father, Golden Deer</em> and <em>Run</em> have won favour on the ether, and after years in the musical underground Korben Dallas has become a trend-setting band. The group was founded by singer and guitarist Juraj Benetin and bass guitarist Lukáš Fila after the break-up of Appendix, where they had played together for thirteen years. After much searching, Ozo Guttler from the Here at Home group became the drummer. The band made its debut with the live album <em>Fine Roads</em> in 2011, and apart from playing in a number of music festivals it has also performed concerts together with the American singer Jess Klein and collaborated with Ľuboš Petruška of Chiki liki tu-a and Andrej Šeban. However, up to now Korben Dallas has never played with an orchestra – here it is in an exclusive premiere, first time in the Viva Musica! Festival, under the baton of Braňo Kostka!",
    "img" : "korben.jpg",
    "path" : "korben-dallas-symphony",
    "tickets" : "http://www.ticketportal.sk/event.aspx?id=19545&idpartner=57",
    "price" : "do 31. mája 2014: 25,- / 20,- / 15,- EUR"
})
db.program.insert({
    "datenum" : 27,
    "datemonth" : "jún",
    "datemonth_en": "June",
    "datetime" : "22:00  <br /><br />24:00 hororová noc v Gorila.sk Urban Space",
    "place" : "Stará tržnica",
    "place_en": "Old City Market Hall",
    "title" : "Upír Nosferatu",
    "title_en": "Nosferatu",
    "intro" : "„Keď sa za Hutterom samé od seba zavreli dvere hradu, jeho osud bol spečatený. Mal sa stať prvou svetoznámou obeťou prvého svetoznámeho upíra a ako mu povedal Dr. Sievers: Svojmu osudu neutečiete.“ (www.kinema.sk)",
    "intro_en": "The legendary silent film with orchestral accompaniment.",
    "text" : "Každý ho pozná, ale málokto ho v súčasnosti naozaj videl. Reč je o klasickom nemeckom nemom filme Upír Nosferatu (Nosferatu, eine Symphonie des Grauens; r. F. W. Murnau, 1922), ktorý už takmer storočie desí obecenstvo na celom svete. Keď sa nemecký expresionista Friedrich Wilhelm Murnau rozhodol natočiť adaptáciu slávneho románu Brama Stokera Dracula netušil, že vytvorí nadčasové dielo, ktoré budú filmoví vedci študovať ešte dlho po jeho smrti, a ktoré položí základy filmového hororu. Mladý úradník realitnej kancelárie Hutter prichádza do Transylvánie na hrad bohatého kupca, grófa Orloka, avšak po jeho návrate už nič nie je tak ako predtým... V rámci Viva Musica! festivalu uvedieme Murnauov film s autorskou hudbou slovenského skladateľa Vladislava Šarišského, laureáta prestížnej Medzinárodnej súťaže Sergeja Prokofieva v Petrohrade a držiteľa Ceny pre mladého tvorcu udeľovanej Nadáciou Tatra banky.<br /><br /><b>Po koncerte v Starej tržnici pokračujeme hororovou nocou v Gorila.sk Urban Space!<br /><br />Príďte sa báť po kultovom Draculovi do Gorila.sk Urban Space. 27. júna o 24:00 na Nám. SNP začína hororová noc. Prinesieme vám tri hororové filmy, ktoré vybrali fanúšikovia tohto žánru. Úplne vážne: návštevu odporúčame len tým, ktorí sa neboja!</b>",
    "text_en": "Everyone knows of it, but at the present day few have actually seen it. We are referring to the classical German silent film Nosferatu (<em>Nosferatu, eine Symphonie des Grauens</em>; dir. F. W. Murnau, 1922), which for almost a century has been frightening audiences throughout the world. When the German expressionist Friedrich Wilhelm Murnau decided to film an adaptation of Bram Stoker’s famous novel Dracula, he had no idea he was about to create a timeless work which would lay the foundations of film horror and would be studied by scholars of film long after his death. A young clerk of the Hutter estate agency comes to Transylvania to the castle of Count Orlok, a wealthy merchant, but after his return nothing is as it was before... As part of the Viva Musica! Festival we are presenting Murnau’s film with music written by the Slovak composer Vladislav “Sun” Šarišský, laureate of the prestigious international Sergej Prokofiev Competition in St. Petersburg and holder of the Young Artist’s Prize awarded by the Tatra Bank Foundation.<br /><br /><em>After the concert in the Old City Market Hall, we continue with the night of horror in Gorila.sk Urban Space! At 24:00, June 27, the night of horror begins at SNP Square. We are bringing you three horror films which fans of this genre have selected. Quite seriously: we recommend a visit only to those who aren’t scared!</em>",
    "img" : "nosferatu.jpg",
    "path" : "upir-nosferatu",
    "tickets" : "http://www.ticketportal.sk/event.aspx?ID=19546&idpartner=57",
    "price" : "do 31. mája 2014: 15,- EUR"
})
db.program.insert({
    "datenum" : 28,
    "datemonth" : "jún",
    "datemonth_en" : "June",
    "datetime" : "20:00",
    "place" : "Bratislavský hrad",
    "place_en": "Bratislava Castle",
    "title" : "Viva Opera!",
    "title_en" : "Viva Opera!",
    "intro" : "Svetoznáme slovenské operné hviezdy po prvýkrát spolu na jednom pódiu!",
    "intro_en": "World-famous opera stars together on one stage for the first time!",
    "text" : "Záverečný koncert 10. ročníka medzinárodného festivalu Viva Musica! bude oslavou opery. Na jednom pódiu sa po prvýkrát spolu stretnú najlepší slovenskí operní sólisti – Adriana Kučerová, Jana Kurucová, Miroslav Dvorský, Dalibor Jenis a Štefan Kocán, ktorí v sprievode Orchestra Viva Musica! pod taktovkou Martina Leginusa, súčasného hudobného riaditeľa a šéfdirigenta pražskej Štátnej opery, uvedú známe i menej známe operné lahôdky z pera takých operných majstrov, akými boli Giuseppe Verdi, Georges Bizet, Gioacchino Rossini či Giacomo Puccini. Viva Opera!",
    "text_en": "The concluding concert of the 10th a celebration of opera. For the first time the finest Slovak opera soloists will meet on the same stage. Adriana Kučerová, Jana Kurucová, Miroslav Dvorský, Dalibor Jenis and Štefan Kocán, accompanied by the Orchestra Viva Musica! under the baton of Martin Leginus, musical director and chief conductor of the Prague State Opera, will perform well-known and less well-known delights of opera, composed by such masters as Giuseppe Verdi, Georges Bizet, Gioacchino Rossini, and Giacomo Puccini. Viva opera! annual international Viva Musica! Festival will be",
    "img" : "opera.jpg",
    "path" : "viva-opera",
    "tickets" : "http://www.ticketportal.sk/event.aspx?id=19471&idpartner=57",
    "price" : "od 15,- EUR"
})
